---
name: AGP

on:
  schedule:
    - cron: "0 0 * * *" # daily

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: AGP
        uses: ms-jpq/auto-github-push@2c564a3a357fba357c1a1e8d89533e6c2db374de
        with:
          token: ${{ secrets.CI_TOKEN }}
